### PR TITLE
Add Autosplitter settings dialog, fix some UI jank

### LINKED ISSUE #36: Linux: Can't close the color change menu
On the layout editor for some reason I am unable to close the color change menu. I am using kde plasma

### PR DESCRIPTION
**Pull request by Scaless**
Added a menu option for editing autosplitter settings. The window supports all of the types that are currently available for autosplitter settings (Title, Bool, Choice, FileSelect).  Autosplitter settings are saved when splits are saved. 

I have tested a few different autosplitters on Linux (kubuntu 25.10) and Windows 11. I am unable to test Mac, however the Github Actions build passed. 

image

image

____________________________

Also fixed are a few UI jank issues:

* All platforms: Clicking a combobox a second time will close the combobox without changing the current selection. 
* All platforms: Clicking a color picker a second time will close the color picker dialog, fixes https://github.com/AlexKnauth/livesplit-one-druid/issues/36 
* Windows: The color picker now appears directly underneath the color button instead of covering it: 
image

Linux: I was unable to fix the issue where dialogs always appear in the top left of the window, this seems like a Druid + Wayland issue that is beyond my abilities. Tooltips on the autosplitter settings also have a titlebar, this seems to also be a Wayland problem. Works fine on Windows.

### CODE REVIEW

**Comment by AlexKnauth** [comment]
I'm getting some janky-looking text-overflowing-outside-the-combo-box behavior:
Transition-with-discontinuities-Transition

**Comment by Scaless** [comment]
That also happened on 0.6.1, it just wasn't apparent because not many options use long text.

Latest change clips the text for the main window and then uses full text width for the dropdown.

image

**Comment by AlexKnauth** [comment]
I'll want to do a bit more testing before I merge, but thank you, this looks very good so far!

**Comment by AlexKnauth** [comment]
The title, check-box, and combo-box settings seem fine, but the File Select setting is not working properly. It's crashing on Mac, and on Windows it's not crashing but it's setting the path to the wrong format: it's supposed to be a WASI-compatible path, not a Windows-format path.

Current wrong path format:
```
C:\foo\bar.lss
```
Corresponding corrected path format:
```
/mnt/c/foo/bar.lss
```

`livesplit-core` has the 2 helper functions `wasi_path::to_native` and `wasi_path::from_native` to convert between these path formats

File: src/autosplitter_editor.rs [hunk 1]
```diff
@@ -0,0 +1,785 @@
...
+                )
+            }
+            WidgetKind::FileSelect { filters } => {
+                let path = settings_map
+                    .and_then(|m| m.get(widget.key.as_ref()))
+                    .and_then(|v| match v {
+                        SettingValue::String(s) => Some(s.clone()),
+                        _ => None,
+                    })
+                    .unwrap_or_else(|| "".into());
```
Comment (AlexKnauth) [inline src/autosplitter_editor.rs]: Around here is where I think would be good to use `wasi_path::to_native`.

File: src/autosplitter_editor.rs [hunk 2]
```diff
@@ -0,0 +1,785 @@
...
+                    SettingRowValue::Bool(b) => SettingValue::Bool(*b),
+                    SettingRowValue::Choice { current, options } => {
+                        if let Some(opt) = options.get(*current) {
+                            SettingValue::String(opt.key.to_string().into())
+                        } else {
+                            continue;
+                        }
+                    }
+                    SettingRowValue::FileSelect { path, .. } => {
+                        SettingValue::String(path.to_string().into())
```
Comment (AlexKnauth) [inline src/autosplitter_editor.rs]: And around here is where it would be good to use `wasi_path::from_native`.

File: src/autosplitter_editor.rs [hunk 3]
```diff
@@ -0,0 +1,785 @@
...
+                        }
+                        break;
+                    }
+                }
+
+                // Also update the runtime's settings map
+                let mut settings_map = data.runtime.settings_map().unwrap_or_default();
+                settings_map.insert(
+                    key.to_string().into(),
+                    SettingValue::String(path_str.to_string().into()),
```
Comment (AlexKnauth) [inline src/autosplitter_editor.rs]: This may also be a place to use `wasi_path::from_native`.

**Review by AlexKnauth — APPROVED** [review]
I've fixed the path format problem on Windows with the commit `wasi_path: to_native, from_native`. I haven't been able to fix the crashing problem on Mac yet, but I figure it's better to merge and work on that myself after merging, since I can test on Mac and you said you were unable to test on Mac.

**Comment by Scaless** [comment]
Sounds good, thanks for merging and fixing the paths! 

For the file open dialog I had to do some funky stuff with opening the file dialog on a separate thread in order to get it working, but that's probably the cause of the issues. There's probably a more integrated way that you're supposed to do it but I couldn't figure it out since Rust/Druid are completely new to me :snake: 

I'm away for a few days but if you don't have it figured out by then I can take another crack at it.
